<?PHP

define("_RECEPIENT_MISSING", "Recepient's username missing!");
define("_NONE", "None");
define("_NO_SUCH_USER_MSG_NOT_SENT", "No such User by the name of ".$_GET['To'].".<br />Your message has NOT been sent!");
define("_MSG_SENT", "Your Message has been sent to ".$_GET['To']."!");
define("_NO_SUCH_MSG", "No such Message with that id was found");
define("_MSG_DELETED", "Message Successfully Deleted!");
define("_SEND_A_MSG", "Send a message");
define("_DELETE", "Delete");
define("_FROM", "From");
define("_SUBJECT", "Subject");
define("_RECIEVED", "Recieved");
define("_NO_MSGS", "You have no Messages");
define("_MESSAGE", "Message");
define("_REPLY", "Reply");
define("_GO_TO_INBOX", "Go to Inbox");
define("_SENT_ON", "Date");
define("_YOU_HAVE", "You have <b>");
define("_NEW_MESSAGES", "</b> New Message(s)!");
define("_NO_NEW_MESSAGES", "You have no New Messages.");
define("_TO", "To");
define("_NEW_AND", "</b>New Message(s)<br />and <b>");
define("_OLD_MESSAGES", "</b> Old Messages!");
define("_ILLEGAL_CHAR_SUBJECT", "Illegal characters in the Subject!");
define("_ILLEGAL_CHAR_TO", "Illegal characters in the \"Recipient\" field!");
define("_DEFAULT_MESSAGE_PM", "I appologize, I forgot to insert my message. So this one was generated by the server for me. :-)");
define("_PAGE", "Page");
define("_NO_MESSAGES_SELECTED_FOR_DELETE", "You did not select any messages to delete!");
define("_QUOTE_REPLY", "Quote & Reply");

?>