INSERT INTO `php_settings` VALUES (
1,
'Welcome to PHPublisher', 
'My site, I own it! Not you!', 
'description', 
'keywords', 
'webmaster@mysite.com', 
1, 
'<div style="text-align: center">PHPublisher has been successfully installed!</div>', 
'PHPublisher', 
0, 
'english', 
1, 
'<b>© 2005 by me. All Rights Reserved.</b> mysite.com  is © copyright by me.', 
'All logos and trademarks in this site are property of their respective owners. The comments are property of their posters, all the rest © 2005 by me. ', 
1, 
'SITE URL GOES HERE REMEMBER NO TRAILING SLASH', 
0, 
1, 
5, 
10, 
1, 
50, 
'START DATE GOES HERE', 
0, 
0, 
500,
1,
'',
'/',
1);	