<?
if(!defined("IN_DB")){
	die("Hacking Attempt!");
}
 $Table->Open(); ?><table width="100%"  border="0" cellspacing="0" cellpadding="0">
  <tr>
    <td align="left">
Terms of use for <?=$Site_Title ?><br>
<p><strong>1. Acceptance of terms of use and amendments</strong><br>
Each time you use or cause access to this web site, you agree to be bound by these terms of use, as amended from time to time with or without notice to you. In addition, if you are using a particular service hosted on or accessed via this web site, you will be subject to any rules or guidelines applicable to the said services, and they will be incorporated by reference within these terms of use. Please refer to this site's <a href="/index.php?find=Members&file=Privacy">privacy policy</a>, which is incorporated within these terms of use by reference.</p>
<p><strong>2. The site editor's service</strong><br>
  This web site and services provided to you on and through this web site are provided on an &quot;AS IS&quot; basis.You agree that the site editor exclusively reserves the right to modify or discontinue provision of this web site and its services, and to delete the data you provide, either temporarily or permanently; the site and may, at any time and without notice and any liability to you, The site editor shall have no responsibility or liability for the timeliness, deletion, failure to store, inaccuracy, or improper delivery of any data or information.</p>
<p><strong>3. Your responsibilities and registration obligations</strong><br>
  In order to use this web site or certain parts of it, you may be required to register a user account on this web site; in this case, you agree to provide truthful information when requested. By registering, you explicitly agree to this site's terms of use, including any amendments made by the site editor from time to time and available here.</p>
<p><strong>4. Privacy policy.</strong><br>
  Registration data and other personally-identifiable information that may be collected on this site is subject to the terms of the site's privacy policy.</p>
<p><strong>5. Registration and password</strong><br>
  You are responsible for maintaining the confidentiality of your password, and shall be responsible for all usage of your user account and/or user name, whether authorized or unauthorized by you. You agree to immediately notify the site editor of any unauthorized use or your user account, user name or password.</p>
<p><strong>6. Your conduct.</strong><br>
  You agree that all information or data of any kind, whether text, software, code, music or sound, photographs or graphics, video or other materials (&quot;content&quot;), made available publicly or privately, shall be under the sole responsibility of the person providing the content or the person whose user account is used. You agree that this web site may expose you to content that may be objectionable or offensive. The site editor shall not be responsible to you in any way for the content that appears on this web site, nor for any error or omission.</p>
<p>By using this web site or any service provided, you explicitly agree that you shall not:<br>
  (a) provide any content or conduct yourself in any way that may be construed as: unlawful; illegal; threatening; harmful; abusive; harassing; stalking; tortuous; defamatory; libelous; vulgar; obscene; offensive; objectionable; pornographic; designed to interfere or interrupt this web site or any service provided, infected with a virus or other destructive or deleterious programming routine; giving rise to civil or criminal liability; or in violation of an applicable local, national or international law;<br>
  (b) impersonate or misrepresent your association with any person or entity; forge or otherwise seek to conceal or misrepresent the origin of any content provided by you;<br>
  (c) collect or harvest any data about other users;<br>
  (d) provide or use this web site for the provision of any content or service in any commercial manner, or in any manner that would involve junk mail, spam, chain letters, pyramid schemes, or any other form of unauthorized advertising, without the site editor's prior written consent; <br>
  (e) provide any content that may give rise to civil or criminal liability of the site editor, or that may constitute or be considered a violation of any local, national or international law, including -- but not limited to -- laws relating to copyright, trademark, patent, or trade secrets.<br>
</p>
<p><strong>7. Submission of content on this web site</strong><br>
  By providing any content to this web site:<br>
  (a) you agree to grant the site editor a worldwide, royalty-free, perpetual, non-exclusive right and license (including any moral rights or other necessary rights.) to use, display, reproduce, modify, adapt, publish, distribute, perform, promote, archive, translate, and to create derivative works and compilations, in whole or in part. Such license will apply with respect to any form, media, technology already known or developed subsequently;<br>
  (b) you warrant and represent that you have all legal, moral, and other rights that may be necessary to grant us the license specified in this section 7;<br>
  (c) you acknowledge and agree that the site editor shall have the right (but not obligation), at the site editor's entire discretion, to refuse to publish, or to remove, or to block access to any content you provide, at any time and for any reason, with or without notice.<br>
</p>
<p><strong>8. Third-party services</strong><br>
  Goods and services of third parties may be advertised and/or made available on or through this web site. Representations made regarding products and services provided by third parties are governed by the policies and representations made by these third parties. The site editor shall not be liable for or responsible in any manner for any of your dealings or interaction with third parties.</p>
<p><strong>9. Indemnification</strong><br>
  You agree to indemnify and hold harmless the site editor and the site editor's subsidiaries, affiliates, related parties, officers, directors, employees, agents, independent contractors, advertisers, partners, and co-branders, from any claim or demand, including reasonable attorney's fees, that may be made by any third party, due to or arising out of your conduct or connection with this web site or service, your provision of content, your violation of these terms of use, or any other violation of the rights of another person or party.</p>
<p><strong>10. DISCLAIMER OF WARRANTIES</strong><br>
  YOU UNDERSTAND AND AGREE THAT YOUR USE OF THIS WEB SITE AND ANY SERVICES OR CONTENT PROVIDED (THE &quot;SERVICE&quot;) IS MADE AVAILABLE AND PROVIDED TO YOU AT YOUR OWN RISK. IT IS PROVIDED TO YOU &quot;AS IS&quot; AND THE SITE EDITOR EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, EITHER IMPLIED OR EXPRESS, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
<p>THE SITE EDITOR MAKES NO WARRANTY, IMPLIED OR EXPRESS, THAT ANY PART OF THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, VIRUS-FREE, TIMELY, SECURE, ACCURATE, RELIABLE, OR OF ANY QUALITY, NOR IS IT WARRANTED EITHER IMPLICITLY OR EXPRESSLY THAT ANY CONTENT IS SAFE IN ANY MANNER FOR DOWNLOAD. YOU UNDERSTAND AND AGREE THAT NEITHER THE SITE EDITOR NOR ANY PARTICIPANT IN THE SERVICE PROVIDES PROFESSIONAL ADVICE OF ANY KIND AND THAT USE OF ANY ADVICE OR ANY OTHER INFORMATION OBTAINED VIA THIS WEB SITE IS SOLELY AT YOUR OWN RISK, AND THAT THE SITE EDITOR MAY NOT BE HELD LIABLE IN ANY WAY.</p>
<p>Some jurisdictions may not allow disclaimers of implied warranties, and certain statements in the above disclaimer may not apply to you as regards implied warranties; the other terms and conditions remain enforceable notwithstanding.</p>
<p><strong>11. LIMITATION OF LIABILITY</strong><br>
  YOU EXPRESSLY UNDERSTAND AND AGREE THAT THE SITE EDTIOR SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INDICENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES; THIS INCLUDES, BUT IS NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSS (EVEN IF THE SITE EDITOR HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM OR ARISING OUT OF (I) THE USE OF OR THE INABILITY TO USE THE SERVICE, (II) THE COST OF OBTAINING SUBSTITUTE GOODS AND/OR SERVICES RESULTING FROM ANY TRANSACTION ENTERED INTO ON THROUGH THE SERVICE, (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA TRANSMISSIONS, (IV) STATEMENTS BY ANY THIRD PARTY OR CONDUCT OF ANY THIRD PARTY USING THE SERVICE, OR (V) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
<p>In some jurisdictions, it is not permitted to limit liability and, therefore, such limitations may not apply to you.<br>
</p>
<p><strong>12. Reservation of rights</strong><br>
  The site editor reserves all of the site editor's rights, including but not limited to any and all copyrights, trademarks, patents, trade secrets, and any other proprietary right that the site editor may have for this web site, its content, and the goods and services that may be provided. The use of the site editor's rights. and property requires the site editor's prior written consent. By making services available to you, the site editor is not providing you with any implied or express licenses or rights, and you will have no rights. to make any commercial uses of this web site or service without the site editor's prior written consent.</p>
<p><strong>13. Notification of copyright infringement</strong><br>
  If you believe that your property has been used in any way that would be considered a copyright infringement or a violation of your intellectual property rights, the site editor's copyright agent may be contacted at the following address:</p>
<p>E-Mail the webmaster here: 
<?=$Admin_Email ?></p>
<p>[Other contact information including address or information concerning a designated agent]</p>
<p><strong>14. Applicable law</strong><br>
  You agree that these terms of use and any dispute arising out of your use of this web site or the site editor's products or services shall be governed by and construed in accordance with local laws in force where the headquarters of the owner of this web site is located, without regard to its conflict of law provisions. By registering or using this web site and service, you consent and submit to the exclusive jurisdiction and venue of the location of the headquarters of the owner of this web site.</p>
<p><strong>15. Miscellaneous information</strong><br>
(ID 1033 0 1) In the event that these terms of use conflict with any law under which any provision may be held invalid by a court with jurisdiction over the parties, such provision will be interpreted to reflect the original intentions of the parties in accordance with applicable law, and the remainder of these terms of use will remain valid and intact; (ii) The failure of either party to assert any right under these terms of use shall not be considered a waiver of that party's right, and that right will remain in full force and effect; (iii) You agree that, without regard to any statute or contrary law, that any claim or cause arising out of this web site or its services must be filed within one (1) year after such claim or cause arose, or else the claim shall be forever barred; (iv) The site editor may assign the site editor\;s rights and obligations under these terms of use; in this case, the site editor shall be relieved of any further obligation.</p></td>
  </tr>
</table>
<? $Table->Close(); ?>